# -*- coding: utf-8 -*-
"""iris_train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18B7izFWM0-S01vEJFAiRxwq_WgLjjdL3
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import joblib
import gdown
file_path = '/content/drive/MyDrive/Iris_Dataset/Iris.csv'

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = pd.read_csv(file_path)
df

X = df.drop(columns=["Id","Species"])

y = df["Species"]

model = RandomForestClassifier(n_estimators=100, max_depth=3, random_state=42)
model.fit(X, y)

predictions = model.predict(X_test)
score = accuracy_score(y_test, predictions)
score

joblib.dump(model, 'iris_model.joblib')
print("✅ iris_model.joblib created successfully!")

def load_data():
    gdown.download('iris_model.joblib', quiet=False)

