# -*- coding: utf-8 -*-
"""iris_train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18B7izFWM0-S01vEJFAiRxwq_WgLjjdL3
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import joblib
import gdown
file_path = '/content/drive/MyDrive/Iris_Dataset/Iris.csv'

from sklearn.tree import DecisionTreeClassifier


df = pd.read_csv(file_path)
df

X = df.drop(columns=["Id","Species"])

y = df["Species"]

model = DecisionTreeClassifier()
model.fit(X, y)

joblib.dump(model, 'iris_model.joblib')
print("✅ iris_model.joblib created successfully!")

def load_data():
    gdown.download('iris_model.joblib', quiet=False)

